# Generated by Django 4.2 on 2025-09-19 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2025, 9, 19, 10, 24, 14, 374150))), name='Please check event date'),
        ),
    ]
