# Generated by Django 4.2 on 2025-09-19 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_please_check_event_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Please check event date',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2025, 9, 19, 10, 24, 32, 510147))), name='Please check event date'),
        ),
    ]
