# Generated by Django 4.2 on 2025-09-19 09:40

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person'},
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=30, validators=[Person.models.valide_email]),
        ),
    ]
